### ISSUE TITLE
MC Country for EE3

### ISSUE THREAD

**Issue by timardex** [proimage/mc_country#2]
Hi! 

I found your MC Country plugin for EE2 and I would like to ask that do you have plan to make it compatible for EE3 as well? Or if not, can you please give me some informaton how to make it compatible for EE3? Thank you in addvance!

Regards,
timardex

**Comment by proimage** [comment]
I don't have any such plans, sorry. Most of my work involving EE has ended, and the demands on my time have pulled me in a different direction than EE.

The conversion process for plugins is documented [here](https://docs.expressionengine.com/latest/development/conversion/index.html); that would be a good place to start. Since MC Country is merely a plugin, the process _should_ be fairly straight-forward.

**Comment by sparkison** [comment]
I just created a [pull request](https://github.com/proimage/mc_country/pull/3) that adds EE3 support for this plugin ;)

**Comment by proimage** [comment]
Merged #3.
